package counter;

public class About extends javax.swing.JFrame
{

    /**
     * Creates new form About
     */
    public About()
    {
        initComponents();
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutMenuButton = new javax.swing.JButton();
        aboutExitButton = new javax.swing.JButton();
        aboutScrollPane = new javax.swing.JScrollPane();
        aboutTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABOUT");
        setName("About_Fame"); // NOI18N

        aboutMenuButton.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        aboutMenuButton.setText("MENU");
        aboutMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuButtonActionPerformed(evt);
            }
        });

        aboutExitButton.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        aboutExitButton.setText("EXIT");
        aboutExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutExitButtonActionPerformed(evt);
            }
        });

        aboutTextArea.setEditable(false);
        aboutTextArea.setBackground(new java.awt.Color(0, 0, 0));
        aboutTextArea.setColumns(20);
        aboutTextArea.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        aboutTextArea.setForeground(new java.awt.Color(255, 255, 0));
        aboutTextArea.setRows(5);
        aboutTextArea.setText("AHSANULLAH UNIVERSITY OF SCIENCE AND TECNOLOGY\n---------------------------------------------------------------------\nCOURSE TITLE  : SOFTWARE DEVELOPMENT LAB - II ( JAVA )\nCOURSE NO     : CSE 2106    |||||           YEAR   : 2ND\nDEPARTMENT  : CSE             \\\\\\\\     SEMESTER : 1ST\nGROUP               : 2                  ////      SECTION : B2\n--------------------------------------------------------------------\nSUMITTED BY :\nMD . ZAFIR ALVI                                         |||    ID : 14.02.04.084\nMD. SADIQ MAHBUB FAISAL SHISHIR  |||    ID : 14.02.04.087\nMD. TOUHIDUL ISLAM                             |||    ID : 14.02.04.088\n\nCOURSE TEACHER : MD. TAWSEEF ALAM\n----------------------------------------------------------------------\nTHIS SOFTWARE WAS MADE AS A PROJECT OF OUR SOFTWARE \nDEVELOPMENT LAB OF JAVA . WE HAVE USED \"BEANSHELL\"\nLIBRARY TO HANDLE NORMAL SCIENTIFIC OPERATIONS AND\n\"FLANAGAN\" FOR HANDLING COMPLEX OPERATIONS.\nALTHOUGH AT THE BEGINNING OF THE PROJECT WE PLANNED TO ADD MANY FEATURES \nIN OUR CALCULATOR , WE HAVE TO WORK AGAINST LIMITED\nTIME  AND THERE WE HAVE STOPPED . AS A BEGINNER OF GUI\nPROGRAMMING , IT TOOK LONG TIME TO DO MANY EASY \nIMPLEMENTATIONS . IN SPITE OF WORKING UNDER PRESSURE\n,WE ENJOYED A LOT AS IT WAS THE FIRST TIME , WE WERE \nEXCITED AS WE ARE MAKING A SOFTWARE ( THOUGH IT \nMIGHTBE A SIMPLE PROJECT AND THERE MAYBE SOME SMALL\nDRAWBACKS ) .OUR TEACHER WAS VERY HELPFUL .\n\nWE WILL MISS THE TIME THAT WE HAD SPENT .\n\nHOPE WE CAN DO BETTER IN FUTURE . \nPRAY FOR OUR SUCCESS .\n-------------------------11/2/2016,11:06 PM----------------------");
        aboutScrollPane.setViewportView(aboutTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aboutMenuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aboutExitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(aboutScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutMenuButton)
                    .addComponent(aboutExitButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(623, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutMenuButtonActionPerformed
    {//GEN-HEADEREND:event_aboutMenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu object = new Menu();
        object.setVisible(true);
    }//GEN-LAST:event_aboutMenuButtonActionPerformed

    private void aboutExitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutExitButtonActionPerformed
    {//GEN-HEADEREND:event_aboutExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_aboutExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutExitButton;
    private javax.swing.JButton aboutMenuButton;
    private javax.swing.JScrollPane aboutScrollPane;
    private javax.swing.JTextArea aboutTextArea;
    // End of variables declaration//GEN-END:variables
}
