package counter;
import java.io.*;
//import function to convert
import functions.NumberSystem;
public class CALCULATOR_NumberSystemConvert extends javax.swing.JFrame
{
    NumberSystem object = new NumberSystem();
    
    public String fromComboString , toComboString ;
    public String[] fromList = new String[]{"(from)","decimal","binary","octal","hexadecimal"};
    public String[] toList = new String[]{"(to)","decimal","binary","octal","hexadecimal"};
    /*
    public String binaryToDecimalConversion(String binary )
    {
        return ""+Integer.parseInt(binary,2);      
    }
    public String octalToDecimalConversion(String octal )
    {
        return ""+Integer.parseInt(octal,8);      
    }
    public String hexadecimalToDecimalConversion(String hexadecimal)
    {
        return ""+Integer.parseInt(hexadecimal,16);      
    }
    */
    public CALCULATOR_NumberSystemConvert()
    {
        initComponents();
        getContentPane().setBackground(java.awt.Color.PINK);
        //Initialize from combo box
        numberSystemConvertFromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(fromList));
        numberSystemConvertToComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(toList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        numberSystemConvertInputTextField = new javax.swing.JTextField();
        numberSystemConvertOutputTextField = new javax.swing.JTextField();
        numberSystemConvertFromComboBox = new javax.swing.JComboBox<>();
        numberSystemConvertToComboBox = new javax.swing.JComboBox<>();
        numberSystemConvertConvertButton = new javax.swing.JButton();
        numberSystemConvertZeroButton = new javax.swing.JButton();
        numberSystemConvertOneButton = new javax.swing.JButton();
        numberSystemConvertTwoButton = new javax.swing.JButton();
        numberSystemConvertThreeButton = new javax.swing.JButton();
        numberSystemConvertFourButton = new javax.swing.JButton();
        numberSystemConvertFiveButton = new javax.swing.JButton();
        numberSystemConvertSixButton = new javax.swing.JButton();
        numberSystemConvertSevenButton = new javax.swing.JButton();
        numberSystemConvertEightButton = new javax.swing.JButton();
        numberSystemConvertNineButton = new javax.swing.JButton();
        numberSystemConvertAButton = new javax.swing.JButton();
        numberSystemConvertBButton = new javax.swing.JButton();
        numberSystemConvertCButton = new javax.swing.JButton();
        numberSystemConvertDButton = new javax.swing.JButton();
        numberSystemConvertEButton = new javax.swing.JButton();
        numberSystemConvertFButton = new javax.swing.JButton();
        numberSystemConvertBackspaceButton = new javax.swing.JButton();
        numberSystemConvertClearButton = new javax.swing.JButton();
        numberSystemConvertAnswerButton = new javax.swing.JButton();
        numberSystemConvertBackToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUMBER SYSTEM CONVERTER");
        setName("CALCULATOR_NumberSystemConvert_Frame"); // NOI18N

        numberSystemConvertInputTextField.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemConvertInputTextField.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertInputTextField.setForeground(new java.awt.Color(0, 255, 0));

        numberSystemConvertOutputTextField.setEditable(false);
        numberSystemConvertOutputTextField.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemConvertOutputTextField.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertOutputTextField.setForeground(new java.awt.Color(0, 255, 0));

        numberSystemConvertFromComboBox.setBackground(new java.awt.Color(0, 0, 255));
        numberSystemConvertFromComboBox.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertFromComboBox.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemConvertFromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        numberSystemConvertFromComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertFromComboBoxActionPerformed(evt);
            }
        });

        numberSystemConvertToComboBox.setBackground(new java.awt.Color(0, 0, 255));
        numberSystemConvertToComboBox.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertToComboBox.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemConvertToComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        numberSystemConvertConvertButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertConvertButton.setText("CONVERT");
        numberSystemConvertConvertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertConvertButtonActionPerformed(evt);
            }
        });

        numberSystemConvertZeroButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertZeroButton.setText("0");
        numberSystemConvertZeroButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertZeroButtonActionPerformed(evt);
            }
        });

        numberSystemConvertOneButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertOneButton.setText("1");
        numberSystemConvertOneButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertOneButtonActionPerformed(evt);
            }
        });

        numberSystemConvertTwoButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertTwoButton.setText("2");
        numberSystemConvertTwoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertTwoButtonActionPerformed(evt);
            }
        });

        numberSystemConvertThreeButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertThreeButton.setText("3");
        numberSystemConvertThreeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertThreeButtonActionPerformed(evt);
            }
        });

        numberSystemConvertFourButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertFourButton.setText("4");
        numberSystemConvertFourButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertFourButtonActionPerformed(evt);
            }
        });

        numberSystemConvertFiveButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertFiveButton.setText("5");
        numberSystemConvertFiveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertFiveButtonActionPerformed(evt);
            }
        });

        numberSystemConvertSixButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertSixButton.setText("6");
        numberSystemConvertSixButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertSixButtonActionPerformed(evt);
            }
        });

        numberSystemConvertSevenButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertSevenButton.setText("7");
        numberSystemConvertSevenButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertSevenButtonActionPerformed(evt);
            }
        });

        numberSystemConvertEightButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertEightButton.setText("8");
        numberSystemConvertEightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertEightButtonActionPerformed(evt);
            }
        });

        numberSystemConvertNineButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertNineButton.setText("9");
        numberSystemConvertNineButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertNineButtonActionPerformed(evt);
            }
        });

        numberSystemConvertAButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertAButton.setText("A");
        numberSystemConvertAButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertAButtonActionPerformed(evt);
            }
        });

        numberSystemConvertBButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertBButton.setText("B");
        numberSystemConvertBButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertBButtonActionPerformed(evt);
            }
        });

        numberSystemConvertCButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertCButton.setText("C");
        numberSystemConvertCButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertCButtonActionPerformed(evt);
            }
        });

        numberSystemConvertDButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertDButton.setText("D");
        numberSystemConvertDButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertDButtonActionPerformed(evt);
            }
        });

        numberSystemConvertEButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertEButton.setText("E");
        numberSystemConvertEButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertEButtonActionPerformed(evt);
            }
        });

        numberSystemConvertFButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertFButton.setText("F");
        numberSystemConvertFButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertFButtonActionPerformed(evt);
            }
        });

        numberSystemConvertBackspaceButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertBackspaceButton.setText("BACKSPACE");
        numberSystemConvertBackspaceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertBackspaceButtonActionPerformed(evt);
            }
        });

        numberSystemConvertClearButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertClearButton.setText("CLEAR");
        numberSystemConvertClearButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertClearButtonActionPerformed(evt);
            }
        });

        numberSystemConvertAnswerButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertAnswerButton.setText("ANSWER");
        numberSystemConvertAnswerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertAnswerButtonActionPerformed(evt);
            }
        });

        numberSystemConvertBackToMenuButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemConvertBackToMenuButton.setText("MENU");
        numberSystemConvertBackToMenuButton.setToolTipText("");
        numberSystemConvertBackToMenuButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numberSystemConvertBackToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberSystemConvertOutputTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberSystemConvertBackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberSystemConvertAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberSystemConvertAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numberSystemConvertEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberSystemConvertBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numberSystemConvertFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberSystemConvertNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numberSystemConvertDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberSystemConvertEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberSystemConvertCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numberSystemConvertClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberSystemConvertConvertButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numberSystemConvertOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numberSystemConvertFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numberSystemConvertTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(numberSystemConvertSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(numberSystemConvertThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(numberSystemConvertSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numberSystemConvertZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numberSystemConvertFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(numberSystemConvertFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(numberSystemConvertToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberSystemConvertInputTextField)
                    .addComponent(numberSystemConvertBackToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberSystemConvertInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberSystemConvertOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberSystemConvertBackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberSystemConvertToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberSystemConvertFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberSystemConvertCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberSystemConvertFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(numberSystemConvertClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberSystemConvertTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberSystemConvertThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberSystemConvertBackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberSystemConvertAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(numberSystemConvertConvertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        setSize(new java.awt.Dimension(527, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numberSystemConvertFromComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertFromComboBoxActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertFromComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberSystemConvertFromComboBoxActionPerformed

    private void numberSystemConvertConvertButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertConvertButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertConvertButtonActionPerformed
        
// TODO add your handling code here:
String s1 =  fromComboString = numberSystemConvertFromComboBox.getSelectedItem().toString();
String s2 = toComboString = numberSystemConvertToComboBox.getSelectedItem().toString();
int flag = 0;

if(numberSystemConvertInputTextField.getText().equals(""))
{
    flag = 1;
}
if(flag==0)
{
    try
    {
        if(s1.equals(s2))
        {
            numberSystemConvertOutputTextField.setText(numberSystemConvertInputTextField.getText());
        }
        else if(s1.equals("decimal")&&s2.equals("binary"))
        {
            numberSystemConvertOutputTextField.setText(Integer.toBinaryString(Integer.parseInt(numberSystemConvertInputTextField.getText())));
        }
        else if(s1.equals("decimal")&&s2.equals("octal"))
        {
            numberSystemConvertOutputTextField.setText(Integer.toOctalString(Integer.parseInt(numberSystemConvertInputTextField.getText())));
        }
        else if(s1.equals("decimal")&&s2.equals("hexadecimal"))
        {
            numberSystemConvertOutputTextField.setText(Integer.toHexString(Integer.parseInt(numberSystemConvertInputTextField.getText())));
        }
        
//-------------------------------------------------------------------------------------

        else if(s1.equals("binary")&&s2.equals("decimal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"binary");
            int finalInt = Integer.parseInt(get2);
            numberSystemConvertOutputTextField.setText(""+finalInt);
        }
        else if(s1.equals("binary")&&s2.equals("octal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"binary");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toOctalString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        else if(s1.equals("binary")&&s2.equals("hexadecimal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"binary");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toHexString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        
//----------------------------------------------------------------

        else if(s1.equals("octal")&&s2.equals("decimal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"octal");
            int finalInt = Integer.parseInt(get2);
            numberSystemConvertOutputTextField.setText(""+finalInt);
        }
        else if(s1.equals("octal")&&s2.equals("binary"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"octal");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toBinaryString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        else if(s1.equals("octal")&&s2.equals("hexadecimal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"octal");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toHexString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        
//------------------------------------------------------------------

        else if(s1.equals("hexadecimal")&&s2.equals("decimal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"hexadecimal");
            int finalInt = Integer.parseInt(get2);
            numberSystemConvertOutputTextField.setText(""+finalInt);
        }
        else if(s1.equals("hexadecimal")&&s2.equals("binary"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"hexadecimal");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toBinaryString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        else if(s1.equals("hexadecimal")&&s2.equals("octal"))
        {
            String get1 = numberSystemConvertInputTextField.getText();
            String get2 = object.convertToDecimalNumberSystem(get1,"hexadecimal");
            int finalInt = Integer.parseInt(get2);
            String get3 = Integer.toOctalString(finalInt);
            numberSystemConvertOutputTextField.setText(""+get3);
        }
        
//-------------------------------------------------------------------

    }
    catch(Exception e)
    {

    }
}
    }//GEN-LAST:event_numberSystemConvertConvertButtonActionPerformed

    private void numberSystemConvertZeroButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertZeroButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertZeroButtonActionPerformed
        // TODO add your handling code here:
        String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertZeroButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
        
    }//GEN-LAST:event_numberSystemConvertZeroButtonActionPerformed

    private void numberSystemConvertBackspaceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertBackspaceButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertBackspaceButtonActionPerformed
        // TODO add your handling code here:
                int isInputEmptyFlag=0;
        String s0 = numberSystemConvertInputTextField.getText();
        if(s0.equals(""))
        {
            isInputEmptyFlag=1;
        }
        if(isInputEmptyFlag==0)
        {
            String oldString,newString;
            oldString=numberSystemConvertInputTextField.getText();
            int oldStringLength = oldString.length();
            int index = oldStringLength-1;
            newString=oldString.substring(0,index);
            numberSystemConvertInputTextField.setText(newString);
        }   
    }//GEN-LAST:event_numberSystemConvertBackspaceButtonActionPerformed

    private void numberSystemConvertClearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertClearButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertClearButtonActionPerformed
        // TODO add your handling code here:
        numberSystemConvertInputTextField.setText("");
        numberSystemConvertOutputTextField.setText("");
    }//GEN-LAST:event_numberSystemConvertClearButtonActionPerformed

    private void numberSystemConvertOneButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertOneButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertOneButtonActionPerformed
        // TODO add your handling code here:
        String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertOneButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertOneButtonActionPerformed

    private void numberSystemConvertTwoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertTwoButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertTwoButtonActionPerformed
        // TODO add your handling code here:
        String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertTwoButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertTwoButtonActionPerformed

    private void numberSystemConvertThreeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertThreeButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertThreeButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertThreeButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertThreeButtonActionPerformed

    private void numberSystemConvertFourButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertFourButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertFourButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertFourButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertFourButtonActionPerformed

    private void numberSystemConvertFiveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertFiveButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertFiveButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertFiveButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertFiveButtonActionPerformed

    private void numberSystemConvertSixButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertSixButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertSixButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertSixButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertSixButtonActionPerformed

    private void numberSystemConvertSevenButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertSevenButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertSevenButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertSevenButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertSevenButtonActionPerformed

    private void numberSystemConvertEightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertEightButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertEightButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertEightButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertEightButtonActionPerformed

    private void numberSystemConvertNineButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertNineButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertNineButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertNineButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertNineButtonActionPerformed

    private void numberSystemConvertAButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertAButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertAButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertAButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertAButtonActionPerformed

    private void numberSystemConvertBButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertBButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertBButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertBButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertBButtonActionPerformed

    private void numberSystemConvertCButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertCButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertCButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertCButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertCButtonActionPerformed

    private void numberSystemConvertDButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertDButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertDButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertDButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertDButtonActionPerformed

    private void numberSystemConvertEButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertEButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertEButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertEButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertEButtonActionPerformed

    private void numberSystemConvertFButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertFButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertFButtonActionPerformed
        // TODO add your handling code here:
                String s1 , s2 , s3 ;
        s1=numberSystemConvertInputTextField.getText();
        s2=numberSystemConvertFButton.getText();
        s3=s1+s2;
        numberSystemConvertInputTextField.setText(s3);
    }//GEN-LAST:event_numberSystemConvertFButtonActionPerformed

    private void numberSystemConvertAnswerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertAnswerButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertAnswerButtonActionPerformed
        // TODO add your handling code here:
        String s1 = numberSystemConvertInputTextField.getText();
        int flag = 0 ;
        if(s1.equals(""))
        {
            flag=1;
        }
        if(flag==0)
        {
            numberSystemConvertInputTextField.setText(numberSystemConvertOutputTextField.getText());
        }
    }//GEN-LAST:event_numberSystemConvertAnswerButtonActionPerformed

    private void numberSystemConvertBackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemConvertBackToMenuButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemConvertBackToMenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu object = new Menu();
        object.setVisible(true);
    }//GEN-LAST:event_numberSystemConvertBackToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CALCULATOR_NumberSystemConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton numberSystemConvertAButton;
    private javax.swing.JButton numberSystemConvertAnswerButton;
    private javax.swing.JButton numberSystemConvertBButton;
    private javax.swing.JButton numberSystemConvertBackToMenuButton;
    private javax.swing.JButton numberSystemConvertBackspaceButton;
    private javax.swing.JButton numberSystemConvertCButton;
    private javax.swing.JButton numberSystemConvertClearButton;
    private javax.swing.JButton numberSystemConvertConvertButton;
    private javax.swing.JButton numberSystemConvertDButton;
    private javax.swing.JButton numberSystemConvertEButton;
    private javax.swing.JButton numberSystemConvertEightButton;
    private javax.swing.JButton numberSystemConvertFButton;
    private javax.swing.JButton numberSystemConvertFiveButton;
    private javax.swing.JButton numberSystemConvertFourButton;
    private javax.swing.JComboBox<String> numberSystemConvertFromComboBox;
    private javax.swing.JTextField numberSystemConvertInputTextField;
    private javax.swing.JButton numberSystemConvertNineButton;
    private javax.swing.JButton numberSystemConvertOneButton;
    private javax.swing.JTextField numberSystemConvertOutputTextField;
    private javax.swing.JButton numberSystemConvertSevenButton;
    private javax.swing.JButton numberSystemConvertSixButton;
    private javax.swing.JButton numberSystemConvertThreeButton;
    private javax.swing.JComboBox<String> numberSystemConvertToComboBox;
    private javax.swing.JButton numberSystemConvertTwoButton;
    private javax.swing.JButton numberSystemConvertZeroButton;
    // End of variables declaration//GEN-END:variables
}
