package counter;

import java.lang.*;

//  ax2 + bx + c = 0
//  ax3 + bx2 + cx + d = 0
// 2x3   - 4x2   - 22x + 24 = 0

public class CALCULATOR_EQUN_MODE extends javax.swing.JFrame {
   

    public String typeComboString , numberComboString ;
    
    public String[] equationType = new String[]{"(select type)","unknown","degree"};
    public String[] unknownTypeNumber = new String[]{"(select equation number)","2","3"};
    public String[] degreeTypeNumber = new String[]{"(select degree number)","2","3"};
    
    public void setInvisible()
    {
        equationLabel0.setVisible(false);
        equationLabel1.setVisible(false);
        equationLabel2.setVisible(false);
        equationLabel3.setVisible(false);
        equationLabel4.setVisible(false);
        equationLabel5.setVisible(false);
        equationLabel6.setVisible(false);
        equationLabel7.setVisible(false);
        equationLabel8.setVisible(false);
        equationLabel9.setVisible(false);
        equationLabel10.setVisible(false);
        equationLabel11.setVisible(false);
        equationLabel12.setVisible(false);
        equationInputTextField1.setVisible(false);
        equationInputTextField2.setVisible(false);
        equationInputTextField3.setVisible(false);
        equationInputTextField4.setVisible(false);      
        equationInputTextField5.setVisible(false);
        equationInputTextField6.setVisible(false);
        equationInputTextField7.setVisible(false);
        equationInputTextField8.setVisible(false); 
        equationInputTextField9.setVisible(false);
        equationInputTextField10.setVisible(false);
        equationInputTextField11.setVisible(false);
        equationInputTextField12.setVisible(false); 
        equationResultButton.setVisible(false);    
    }
      
    public CALCULATOR_EQUN_MODE() {        
        initComponents();
        //initially invisible
        getContentPane().setBackground(java.awt.Color.RED);
        setInvisible();
        //Initialize the typecomboBox 
        equationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(equationType));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equationOutputTextField = new javax.swing.JTextField();
        equationTypeComboBox = new javax.swing.JComboBox<>();
        equationQuantityCounterComboBox = new javax.swing.JComboBox<>();
        equationSelectButton = new javax.swing.JButton();
        equationInputTextField1 = new javax.swing.JTextField();
        equationInputTextField2 = new javax.swing.JTextField();
        equationInputTextField3 = new javax.swing.JTextField();
        equationInputTextField4 = new javax.swing.JTextField();
        equationLabel1 = new javax.swing.JLabel();
        equationLabel2 = new javax.swing.JLabel();
        equationLabel3 = new javax.swing.JLabel();
        equationLabel4 = new javax.swing.JLabel();
        equationLabel0 = new javax.swing.JLabel();
        equationResultButton = new javax.swing.JButton();
        equationInputTextField5 = new javax.swing.JTextField();
        equationLabel5 = new javax.swing.JLabel();
        equationInputTextField6 = new javax.swing.JTextField();
        equationLabel6 = new javax.swing.JLabel();
        equationInputTextField7 = new javax.swing.JTextField();
        equationLabel7 = new javax.swing.JLabel();
        equationInputTextField8 = new javax.swing.JTextField();
        equationLabel8 = new javax.swing.JLabel();
        equationInputTextField9 = new javax.swing.JTextField();
        equationLabel9 = new javax.swing.JLabel();
        equationLabel10 = new javax.swing.JLabel();
        equationInputTextField10 = new javax.swing.JTextField();
        equationInputTextField11 = new javax.swing.JTextField();
        equationLabel11 = new javax.swing.JLabel();
        equationInputTextField12 = new javax.swing.JTextField();
        equationLabel12 = new javax.swing.JLabel();
        equationBackToMenuButton = new javax.swing.JButton();
        equationClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EQUATION SOLVER");
        setName("CALCULATOR_EQUN_MODE_Frame"); // NOI18N

        equationOutputTextField.setEditable(false);
        equationOutputTextField.setBackground(new java.awt.Color(0, 0, 0));
        equationOutputTextField.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationOutputTextField.setForeground(new java.awt.Color(0, 255, 0));

        equationTypeComboBox.setBackground(new java.awt.Color(0, 0, 255));
        equationTypeComboBox.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationTypeComboBox.setForeground(new java.awt.Color(0, 255, 0));
        equationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        equationTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationTypeComboBoxActionPerformed(evt);
            }
        });

        equationQuantityCounterComboBox.setBackground(new java.awt.Color(0, 0, 255));
        equationQuantityCounterComboBox.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationQuantityCounterComboBox.setForeground(new java.awt.Color(0, 255, 0));
        equationQuantityCounterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        equationSelectButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationSelectButton.setText("SELECT");
        equationSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationSelectButtonActionPerformed(evt);
            }
        });

        equationInputTextField1.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField1.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField1.setForeground(new java.awt.Color(0, 255, 0));

        equationInputTextField2.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField2.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField2.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField2ActionPerformed(evt);
            }
        });

        equationInputTextField3.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField3.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField3.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField3ActionPerformed(evt);
            }
        });

        equationInputTextField4.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField4.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField4.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField4ActionPerformed(evt);
            }
        });

        equationLabel1.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel1.setText("jLabel1");

        equationLabel2.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel2.setText("jLabel2");

        equationLabel3.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel3.setText("jLabel3");

        equationLabel4.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel4.setText("jLabel4");

        equationLabel0.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel0.setText("-------------------------------Enter Your Equation--------------------------------");

        equationResultButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationResultButton.setText("RESULT");
        equationResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationResultButtonActionPerformed(evt);
            }
        });

        equationInputTextField5.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField5.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField5.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField5ActionPerformed(evt);
            }
        });

        equationLabel5.setBackground(new java.awt.Color(0, 0, 0));
        equationLabel5.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel5.setText("jLabel5");

        equationInputTextField6.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField6.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField6.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField6ActionPerformed(evt);
            }
        });

        equationLabel6.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel6.setText("jLabel6");

        equationInputTextField7.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField7.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField7.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField7ActionPerformed(evt);
            }
        });

        equationLabel7.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel7.setText("jLabel7");

        equationInputTextField8.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField8.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField8.setForeground(new java.awt.Color(0, 255, 0));

        equationLabel8.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel8.setText("jLabel8");

        equationInputTextField9.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField9.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField9.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField9ActionPerformed(evt);
            }
        });

        equationLabel9.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel9.setText("jLabel9");

        equationLabel10.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel10.setText("jLabel10");

        equationInputTextField10.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField10.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField10.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField10ActionPerformed(evt);
            }
        });

        equationInputTextField11.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField11.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField11.setForeground(new java.awt.Color(0, 255, 0));

        equationLabel11.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel11.setText("jLabel11");

        equationInputTextField12.setBackground(new java.awt.Color(0, 0, 0));
        equationInputTextField12.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationInputTextField12.setForeground(new java.awt.Color(0, 255, 0));
        equationInputTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationInputTextField12ActionPerformed(evt);
            }
        });

        equationLabel12.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationLabel12.setText("jLabel12");

        equationBackToMenuButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationBackToMenuButton.setText("MENU");
        equationBackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationBackToMenuButtonActionPerformed(evt);
            }
        });

        equationClearButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        equationClearButton.setText("CLEAR");
        equationClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equationInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equationInputTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equationInputTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equationLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(equationLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(equationLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(equationInputTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equationInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equationInputTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equationLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equationLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equationLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationInputTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equationLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(equationBackToMenuButton)
                                        .addGap(94, 94, 94)
                                        .addComponent(equationClearButton))
                                    .addComponent(equationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(equationSelectButton)
                                        .addGap(97, 97, 97)
                                        .addComponent(equationResultButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equationQuantityCounterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(equationLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equationOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(equationOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationQuantityCounterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationBackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(equationLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationInputTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationInputTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationInputTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equationLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(936, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void equationTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_equationTypeComboBoxActionPerformed
        // TODO add your handling code here:
        
        if(equationTypeComboBox.getSelectedItem().toString().equals("unknown"))
        {
            equationQuantityCounterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(unknownTypeNumber));
        }
        else if(equationTypeComboBox.getSelectedItem().toString().equals("degree"))
        {
            equationQuantityCounterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(degreeTypeNumber));
        }
    }//GEN-LAST:event_equationTypeComboBoxActionPerformed

    private void equationInputTextField3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField3ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField3ActionPerformed

    private void equationSelectButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationSelectButtonActionPerformed
    {//GEN-HEADEREND:event_equationSelectButtonActionPerformed
        // TODO add your handling code here:
        equationResultButton.setVisible(true);
        setInvisible();
        
        String s1 = typeComboString = equationTypeComboBox.getSelectedItem().toString();
        String s2 = numberComboString = equationQuantityCounterComboBox.getSelectedItem().toString();
        if(s1.equals("degree")&&s2.equals("2"))
        {
            setInvisible();
            equationResultButton.setVisible(true);
            //visible label 0
            equationLabel0.setVisible(true);
            //visible 3 text field
            equationInputTextField1.setVisible(true);
            equationInputTextField2.setVisible(true);
            equationInputTextField3.setVisible(true);
            //visible 3 label
            equationLabel1.setVisible(true);
            equationLabel2.setVisible(true);
            equationLabel3.setVisible(true);
            //set text to the label
            equationLabel1.setText(" x2 + ");
            equationLabel2.setText(" x + ");
            equationLabel3.setText(" = 0 ");
            
            
            
            
            
        }
        else if(s1.equals("degree")&&s2.equals("3"))
        {
            setInvisible();
            equationResultButton.setVisible(true);
            //visible label 0
            equationLabel0.setVisible(true);
            //visible 3 text field
            equationInputTextField1.setVisible(true);
            equationInputTextField2.setVisible(true);
            equationInputTextField3.setVisible(true);
            equationInputTextField4.setVisible(true);
            //visible 3 label
            equationLabel1.setVisible(true);
            equationLabel2.setVisible(true);
            equationLabel3.setVisible(true);
            equationLabel4.setVisible(true);
            //set text to the label
            equationLabel1.setText(" x3 + ");
            equationLabel2.setText(" x2 + ");
            equationLabel3.setText(" x + ");
            equationLabel4.setText(" = 0 ");
        }
        else if(s1.equals("unknown")&&s2.equals("2"))
        {
            setInvisible();
            equationResultButton.setVisible(true);
            //visible label 0
            equationLabel0.setVisible(true);
            //visible 3 text field
            equationInputTextField1.setVisible(true);
            equationInputTextField2.setVisible(true);
            equationInputTextField3.setVisible(true);
            //visible 3 text field
            equationInputTextField5.setVisible(true);
            equationInputTextField6.setVisible(true);
            equationInputTextField7.setVisible(true);
            //visible 3 label
            equationLabel1.setVisible(true);
            equationLabel2.setVisible(true);
            equationLabel3.setVisible(true);
            //visible 3 label
            equationLabel5.setVisible(true);
            equationLabel6.setVisible(true);
            equationLabel7.setVisible(true);
            //set text to the label
            equationLabel1.setText(" x1 + ");
            equationLabel2.setText(" y1 + ");
            equationLabel3.setText(" = 0 ");
            //set text to the label
            equationLabel5.setText(" x2 + ");
            equationLabel6.setText(" y2 + ");
            equationLabel7.setText(" = 0 ");
        }
        else if(s1.equals("unknown")&&s2.equals("3"))
        {
            setInvisible();
            equationResultButton.setVisible(true);
            //visible label 0
            equationLabel0.setVisible(true);
            //visible 4 text field
            equationInputTextField1.setVisible(true);
            equationInputTextField2.setVisible(true);
            equationInputTextField3.setVisible(true);
            equationInputTextField4.setVisible(true);
            //visible 4 text field
            equationInputTextField5.setVisible(true);
            equationInputTextField6.setVisible(true);
            equationInputTextField7.setVisible(true);
            equationInputTextField8.setVisible(true);
            //visible 4 text field
            equationInputTextField9.setVisible(true);
            equationInputTextField10.setVisible(true);
            equationInputTextField11.setVisible(true);
            equationInputTextField12.setVisible(true);
            
            //visible 3 label
            equationLabel1.setVisible(true);
            equationLabel2.setVisible(true);
            equationLabel3.setVisible(true);
  
            //visible 3 label
            equationLabel5.setVisible(true);
            equationLabel6.setVisible(true);
            equationLabel7.setVisible(true);
      
            //visible 3 label
            equationLabel9.setVisible(true);
            equationLabel10.setVisible(true);
            equationLabel11.setVisible(true);
        
            //set text to the label
            equationLabel1.setText(" x1 +");
            equationLabel2.setText(" y1 +");
            equationLabel3.setText(" z1 = ");
            //set text to the label
            equationLabel5.setText(" x2 + ");
            equationLabel6.setText(" y2 + ");
            equationLabel7.setText(" z2 = ");
            //set text to the label
            equationLabel9.setText(" x3 + ");
            equationLabel10.setText(" y3 + ");
            equationLabel11.setText(" z3 = ");
        }
    }//GEN-LAST:event_equationSelectButtonActionPerformed

    private void equationResultButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationResultButtonActionPerformed
    {//GEN-HEADEREND:event_equationResultButtonActionPerformed
        // TODO add your handling code here:
        String s1 = typeComboString = equationTypeComboBox.getSelectedItem().toString();
        String s2 = numberComboString = equationQuantityCounterComboBox.getSelectedItem().toString();
        int flag = 0;

        if(s1.equals("degree")&&s2.equals("2"))
        {
            String f1 = equationInputTextField1.getText();
            String f2 = equationInputTextField2.getText();
            String f3 = equationInputTextField3.getText();
            if(f1.equals("")||f2.equals("")||f3.equals(""))
            {
                flag=1;
            }
            if(flag==0)
            {
                double a = Double.parseDouble(f1);
                double b = Double.parseDouble(f2);
                double c = Double.parseDouble(f3);
                double x1,x2;
                try
                {
                    x1 = (1/(2*a))*(-b+Math.sqrt((Math.pow(b,2)-(4*a*c))));
                    x2 = (1/(2*a))*(-b-Math.sqrt((Math.pow(b,2)-(4*a*c))));
                    equationOutputTextField.setText("First root is : "+x1+" Second root is : "+x2);
                }
                catch(Exception e)
                {
                   equationOutputTextField.setText(e.getMessage());
                }
                
            }
        }
        
        else if(s1.equals("degree")&&s2.equals("3"))
        {
            String f1 = equationInputTextField1.getText();
            String f2 = equationInputTextField2.getText();
            String f3 = equationInputTextField3.getText();
            String f4 = equationInputTextField4.getText();
            if(f1.equals("")||f2.equals("")||f3.equals("")||f4.equals(""))
            {
                flag=1;
            }
            if(flag==0)
            {
                //double a  = 2 , b = -4 ,c =-22 ,d =24;
                
                double a = Double.parseDouble(f1);
                double b = Double.parseDouble(f2);
                double c = Double.parseDouble(f3);
                double d = Double.parseDouble(f4);
                
                double x1,x2,x3;
                try
                {
                double f = (1.0/3.0)*(((3.0*c)/a)-(Math.pow(b,2.0)/Math.pow(a,2.0)));
                        //a = 2 ; b= -4 ; c = -22 ; d= 24;
        //System.out.println("a : "+a+" b : "+b+" c : "+c+" d : "+d);
        double g1 = 1.0/27.0;
        //System.out.println("g1 : "+g1);
        double g2 = (2*Math.pow(b, 3))/Math.pow(a, 3);
        //System.out.println("g2 : "+g2);
        double g3 = ( 9* b*c )/ (Math.pow(a, 2));
        //System.out.println("g3 : "+g3);
        double g4 = (27*d)/a;
       // System.out.println("g4 : "+g4);
        
        double g5 = g2 - g3 + g4 ;
       // System.out.println("g5 : "+g5);
        double g6 = g5/27;
        //System.out.println("g6 : "+g6);
                double g = g6;
                double h = ((Math.pow(g,2.0))/4.0)+((Math.pow(f,3.0))/27.0);
                double i = Math.sqrt(((Math.pow(g,2.0))/4.0)-h);
                double j = Math.cbrt(i);
                double k = Math.acos(-(g/(2.0*i)));
                double l = j*(-1.0);
                double m = Math.cos(k/3.0);
                double n = Math.sqrt(3.0)*Math.sin(k/3.0);
                double p = (-1.0)*(b/(3.0*a));
                x1 = (2.0*j*Math.cos(k/3.0))-(b/(3.0*a));
                x2 = (l*(m+n))+p;
                x3 = (l*(m-n))+p;
                
                    System.out.println("f: "+f+" "+"g: "+g+" "+"h: "+h+" "+"i: "+i+" "+"j: "+j+" "+"k: "+k+" "+"l: "+l+" "+"m: "+m+" "+"n: "+n+" "+"p: "+p);
                
                equationOutputTextField.setText("First root : "+x1+" Second root : "+x2+" Third root : "+x3);
                 // fPrint(2.0,-4.0,-22.0,24.0;
                
                }
                catch(Exception e)
                {
                    equationOutputTextField.setText(e.getMessage());
                }
            }
        }
        else if(s1.equals("unknown")&&s2.equals("2"))
        {
            String f1 = equationInputTextField1.getText();
            String f2 = equationInputTextField2.getText();
            String f3 = equationInputTextField3.getText();
            String f4 = equationInputTextField5.getText();
            String f5 = equationInputTextField6.getText();
            String f6 = equationInputTextField7.getText();
            if(f1.equals("")||f2.equals("")||f3.equals("")||f4.equals("")||f5.equals("")||f6.equals(""))
            {
                flag=1;
            }
            if(flag==0)
            {
                double a1 = Double.parseDouble(f1);
                double b1 = Double.parseDouble(f2);
                double c1 = Double.parseDouble(f3);
                double a2 = Double.parseDouble(f4);
                double b2 = Double.parseDouble(f5);
                double c2 = Double.parseDouble(f6);
                
                double x,y;
                
                
                try{
                    double d = ( a1 * b2 ) - ( a2 * b1 );
                    x = ( (b1*c2) - (b2*c1) )/d;
                    y = ( (c1 * a2) - (c2*a1))/d;
                    
                    equationOutputTextField.setText("x : "+x+" y : "+y);
                
                
                }
                catch(Exception e)
                {
                    equationOutputTextField.setText(e.getMessage());
                }
            
            } 
            
        }
        else if(s1.equals("unknown")&&s2.equals("3"))
        {
            String f1 = equationInputTextField1.getText();
            String f2 = equationInputTextField2.getText();
            String f3 = equationInputTextField3.getText();
            String f4 = equationInputTextField4.getText();
            String f5 = equationInputTextField5.getText();
            String f6 = equationInputTextField6.getText();
            String f7 = equationInputTextField7.getText();
            String f8 = equationInputTextField8.getText();
            String f9 = equationInputTextField9.getText();
            String f10 = equationInputTextField10.getText();
            String f11 = equationInputTextField11.getText();
            String f12 = equationInputTextField12.getText();


            if(f1.equals("")||f2.equals("")||f3.equals("")||f4.equals("")||f5.equals("")||f6.equals("")||f7.equals("")||f8.equals("")||f9.equals("")||f10.equals("")||f11.equals("")||f12.equals(""))
            {
                flag=1;
            }
            if(flag==0)
            {
                double x1 = Double.parseDouble(f1);
                double y1 = Double.parseDouble(f2);
                double z1 = Double.parseDouble(f3);
                double c1 = Double.parseDouble(f4);
                double x2 = Double.parseDouble(f5);
                double y2 = Double.parseDouble(f6);
                double z2 = Double.parseDouble(f7);
                double c2 = Double.parseDouble(f8);
                double x3 = Double.parseDouble(f9);
                double y3 = Double.parseDouble(f10);
                double z3 = Double.parseDouble(f11);
                double c3 = Double.parseDouble(f12);
                
                double a = x1;
                double b = y1;
                double c = z1;
                double d = x2;
                double e = y2;
                double f = z2;
                double g = x3;
                double h = y3;
                double i = z3;
                double j = c1;
                double k = c2;
                double l = c3;
                
                double M,x,y,z;
                M = a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h;
                x = (j*e*i + b*f*l + c*k*h - c*e*l - b*k*i - j*f*h) / M;
                y = (a*k*i + j*f*g + c*d*l - c*k*g - j*d*i - a*f*l) / M;
                z = (a*e*l + b*k*g + j*d*h - j*e*g - b*d*l - a*k*h) / M;
                
                equationOutputTextField.setText("x : "+x+" y : "+y+" z : "+z);
            }

        }
    }//GEN-LAST:event_equationResultButtonActionPerformed

    private void equationInputTextField12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField12ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField12ActionPerformed

    private void equationBackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationBackToMenuButtonActionPerformed
    {//GEN-HEADEREND:event_equationBackToMenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu object = new Menu();
        object.setVisible(true);
    }//GEN-LAST:event_equationBackToMenuButtonActionPerformed

    private void equationInputTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField2ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField2ActionPerformed

    private void equationInputTextField6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField6ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField6ActionPerformed

    private void equationInputTextField7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField7ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField7ActionPerformed

    private void equationClearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationClearButtonActionPerformed
    {//GEN-HEADEREND:event_equationClearButtonActionPerformed
        // TODO add your handling code here:
        equationOutputTextField.setText("");
        equationInputTextField1.setText("");
        equationInputTextField2.setText("");
        equationInputTextField3.setText("");
        equationInputTextField4.setText("");
        equationInputTextField5.setText("");
        equationInputTextField6.setText("");
        equationInputTextField7.setText("");
        equationInputTextField8.setText("");
        equationInputTextField9.setText("");
        equationInputTextField10.setText("");
        equationInputTextField11.setText("");
        equationInputTextField12.setText("");
    }//GEN-LAST:event_equationClearButtonActionPerformed

    private void equationInputTextField5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField5ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField5ActionPerformed

    private void equationInputTextField10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField10ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField10ActionPerformed

    private void equationInputTextField4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField4ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField4ActionPerformed

    private void equationInputTextField9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_equationInputTextField9ActionPerformed
    {//GEN-HEADEREND:event_equationInputTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equationInputTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR_EQUN_MODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR_EQUN_MODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR_EQUN_MODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR_EQUN_MODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULATOR_EQUN_MODE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equationBackToMenuButton;
    private javax.swing.JButton equationClearButton;
    private javax.swing.JTextField equationInputTextField1;
    private javax.swing.JTextField equationInputTextField10;
    private javax.swing.JTextField equationInputTextField11;
    private javax.swing.JTextField equationInputTextField12;
    private javax.swing.JTextField equationInputTextField2;
    private javax.swing.JTextField equationInputTextField3;
    private javax.swing.JTextField equationInputTextField4;
    private javax.swing.JTextField equationInputTextField5;
    private javax.swing.JTextField equationInputTextField6;
    private javax.swing.JTextField equationInputTextField7;
    private javax.swing.JTextField equationInputTextField8;
    private javax.swing.JTextField equationInputTextField9;
    private javax.swing.JLabel equationLabel0;
    private javax.swing.JLabel equationLabel1;
    private javax.swing.JLabel equationLabel10;
    private javax.swing.JLabel equationLabel11;
    private javax.swing.JLabel equationLabel12;
    private javax.swing.JLabel equationLabel2;
    private javax.swing.JLabel equationLabel3;
    private javax.swing.JLabel equationLabel4;
    private javax.swing.JLabel equationLabel5;
    private javax.swing.JLabel equationLabel6;
    private javax.swing.JLabel equationLabel7;
    private javax.swing.JLabel equationLabel8;
    private javax.swing.JLabel equationLabel9;
    private javax.swing.JTextField equationOutputTextField;
    private javax.swing.JComboBox<String> equationQuantityCounterComboBox;
    private javax.swing.JButton equationResultButton;
    private javax.swing.JButton equationSelectButton;
    private javax.swing.JComboBox<String> equationTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
