package counter;

import java.lang.*;
//import functions to calculate number system
import functions.NumberSystem;

public class CALCULATOR_NumberSystemCalculation extends javax.swing.JFrame
{
    NumberSystem object = new NumberSystem();
    public String[] systemTypeList = new String[]{"(Select a type)","decimal","binary","octal","hexadecimal"};
    
    public String binaryToDecimalConversion(String binary )
    {
        return ""+Integer.parseInt(binary,2);      
    }
    public String octalToDecimalConversion(String octal )
    {
        return ""+Integer.parseInt(octal,8);      
    }
    public String hexadecimalToDecimalConversion(String hexadecimal)
    {
        return ""+Integer.parseInt(hexadecimal,16);      
    }
    
    public String inputString,systemTypeComboString;
    
    public CALCULATOR_NumberSystemCalculation()
    {
        initComponents();
        getContentPane().setBackground(java.awt.Color.CYAN);
        //initialize the combo box
        numberSystemCalculationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(systemTypeList));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberSystemCalculationInputTextField1 = new javax.swing.JTextField();
        numberSystemCalculationOutputTextField = new javax.swing.JTextField();
        numberSystemCalculationTypeComboBox = new javax.swing.JComboBox<>();
        numberSystemCalculationAddButton = new javax.swing.JButton();
        numberSystemCalculationSubstractButton = new javax.swing.JButton();
        numberSystemCalculationMultiplyButton = new javax.swing.JButton();
        numberSystemCalculationDivideButton = new javax.swing.JButton();
        numberSystemCalculationInputTextField2 = new javax.swing.JTextField();
        numberSystemCalculationClearButton = new javax.swing.JButton();
        numberSystemCalculationBackToMenuButton = new javax.swing.JButton();
        numberSystemCalculationTypeLabel = new javax.swing.JLabel();
        numberSystemCalculationAnswerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUMBER SYSTEM CALCULATOR");
        setName("CALCULATOR_NumberSystemCalculation_Frame"); // NOI18N

        numberSystemCalculationInputTextField1.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationInputTextField1.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationInputTextField1.setForeground(new java.awt.Color(0, 255, 0));

        numberSystemCalculationOutputTextField.setEditable(false);
        numberSystemCalculationOutputTextField.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationOutputTextField.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationOutputTextField.setForeground(new java.awt.Color(0, 255, 0));

        numberSystemCalculationTypeComboBox.setBackground(new java.awt.Color(0, 0, 255));
        numberSystemCalculationTypeComboBox.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationTypeComboBox.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        numberSystemCalculationTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationTypeComboBoxActionPerformed(evt);
            }
        });

        numberSystemCalculationAddButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationAddButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationAddButton.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationAddButton.setText("ADD");
        numberSystemCalculationAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationAddButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationSubstractButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationSubstractButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationSubstractButton.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationSubstractButton.setText("SUBTRACTION");
        numberSystemCalculationSubstractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationSubstractButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationMultiplyButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationMultiplyButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationMultiplyButton.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationMultiplyButton.setText("MULTIPLY");
        numberSystemCalculationMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationMultiplyButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationDivideButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationDivideButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationDivideButton.setForeground(new java.awt.Color(0, 255, 51));
        numberSystemCalculationDivideButton.setText("DIVIDE");
        numberSystemCalculationDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationDivideButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationInputTextField2.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationInputTextField2.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationInputTextField2.setForeground(new java.awt.Color(0, 255, 0));

        numberSystemCalculationClearButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationClearButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationClearButton.setForeground(new java.awt.Color(255, 0, 0));
        numberSystemCalculationClearButton.setText("CLEAR");
        numberSystemCalculationClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationClearButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationBackToMenuButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationBackToMenuButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationBackToMenuButton.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationBackToMenuButton.setText("MENU");
        numberSystemCalculationBackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationBackToMenuButtonActionPerformed(evt);
            }
        });

        numberSystemCalculationTypeLabel.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        numberSystemCalculationTypeLabel.setText("Select Number System :");

        numberSystemCalculationAnswerButton.setBackground(new java.awt.Color(0, 0, 0));
        numberSystemCalculationAnswerButton.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        numberSystemCalculationAnswerButton.setForeground(new java.awt.Color(0, 255, 0));
        numberSystemCalculationAnswerButton.setText("ANSWER");
        numberSystemCalculationAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSystemCalculationAnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberSystemCalculationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(numberSystemCalculationTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numberSystemCalculationAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberSystemCalculationSubstractButton)
                            .addComponent(numberSystemCalculationMultiplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberSystemCalculationDivideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberSystemCalculationAnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(numberSystemCalculationClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberSystemCalculationInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberSystemCalculationInputTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                            .addComponent(numberSystemCalculationOutputTextField)
                            .addComponent(numberSystemCalculationBackToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberSystemCalculationInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberSystemCalculationInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberSystemCalculationOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberSystemCalculationBackToMenuButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numberSystemCalculationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberSystemCalculationClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberSystemCalculationAddButton)
                                    .addComponent(numberSystemCalculationTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(numberSystemCalculationSubstractButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberSystemCalculationMultiplyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberSystemCalculationDivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberSystemCalculationAnswerButton)
                                .addGap(33, 33, 33))))))
        );

        setSize(new java.awt.Dimension(565, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numberSystemCalculationDivideButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationDivideButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationDivideButtonActionPerformed
        String s1 = numberSystemCalculationInputTextField1.getText();
        String s2 = numberSystemCalculationInputTextField2.getText();
        String s3  = numberSystemCalculationTypeComboBox.getSelectedItem().toString();
        String s4 = object.doMathematicalOperationOnNBasedNumberSystem(s1, s2, s3, "divide");
        numberSystemCalculationOutputTextField.setText(s4);
    }//GEN-LAST:event_numberSystemCalculationDivideButtonActionPerformed

    private void numberSystemCalculationAddButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationAddButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationAddButtonActionPerformed
        String s1 = numberSystemCalculationInputTextField1.getText();
        String s2 = numberSystemCalculationInputTextField2.getText();
        String s3  = numberSystemCalculationTypeComboBox.getSelectedItem().toString();
        String s4 = object.doMathematicalOperationOnNBasedNumberSystem(s1, s2, s3, "add");
        numberSystemCalculationOutputTextField.setText(s4);
        
    }//GEN-LAST:event_numberSystemCalculationAddButtonActionPerformed

    private void numberSystemCalculationSubstractButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationSubstractButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationSubstractButtonActionPerformed
        String s1 = numberSystemCalculationInputTextField1.getText();
        String s2 = numberSystemCalculationInputTextField2.getText();
        String s3 = numberSystemCalculationTypeComboBox.getSelectedItem().toString();
        String s4 = object.doMathematicalOperationOnNBasedNumberSystem(s1, s2, s3, "substract");
        numberSystemCalculationOutputTextField.setText(s4);
    }//GEN-LAST:event_numberSystemCalculationSubstractButtonActionPerformed

    private void numberSystemCalculationMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationMultiplyButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationMultiplyButtonActionPerformed
        String s1 = numberSystemCalculationInputTextField1.getText();
        String s2 = numberSystemCalculationInputTextField2.getText();
        String s3 = numberSystemCalculationTypeComboBox.getSelectedItem().toString();
        String s4 = object.doMathematicalOperationOnNBasedNumberSystem(s1, s2, s3, "multiply");
        numberSystemCalculationOutputTextField.setText(s4);
    }//GEN-LAST:event_numberSystemCalculationMultiplyButtonActionPerformed

    private void numberSystemCalculationBackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationBackToMenuButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationBackToMenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu object = new Menu();
        object.setVisible(true);
    }//GEN-LAST:event_numberSystemCalculationBackToMenuButtonActionPerformed

    private void numberSystemCalculationClearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationClearButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationClearButtonActionPerformed
        // TODO add your handling code here:
        numberSystemCalculationInputTextField1.setText("");
        numberSystemCalculationInputTextField2.setText("");
        numberSystemCalculationOutputTextField.setText("");
    }//GEN-LAST:event_numberSystemCalculationClearButtonActionPerformed

    private void numberSystemCalculationAnswerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationAnswerButtonActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationAnswerButtonActionPerformed
        // TODO add your handling code here:
       String s1 = numberSystemCalculationInputTextField1.getText();
        int flag = 0 ;
       if(s1.equals(""))
        {
            flag=1;
        }
        if(flag==0)
        {
            numberSystemCalculationInputTextField2.setText("");
            numberSystemCalculationInputTextField1.setText(numberSystemCalculationOutputTextField.getText());
        }
    }//GEN-LAST:event_numberSystemCalculationAnswerButtonActionPerformed

    private void numberSystemCalculationTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberSystemCalculationTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_numberSystemCalculationTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberSystemCalculationTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CALCULATOR_NumberSystemCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CALCULATOR_NumberSystemCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton numberSystemCalculationAddButton;
    private javax.swing.JButton numberSystemCalculationAnswerButton;
    private javax.swing.JButton numberSystemCalculationBackToMenuButton;
    private javax.swing.JButton numberSystemCalculationClearButton;
    private javax.swing.JButton numberSystemCalculationDivideButton;
    private javax.swing.JTextField numberSystemCalculationInputTextField1;
    private javax.swing.JTextField numberSystemCalculationInputTextField2;
    private javax.swing.JButton numberSystemCalculationMultiplyButton;
    private javax.swing.JTextField numberSystemCalculationOutputTextField;
    private javax.swing.JButton numberSystemCalculationSubstractButton;
    private javax.swing.JComboBox<String> numberSystemCalculationTypeComboBox;
    private javax.swing.JLabel numberSystemCalculationTypeLabel;
    // End of variables declaration//GEN-END:variables
}
