package counter;

public class Menu extends javax.swing.JFrame
{
    public Menu()
    {
        initComponents();
        getContentPane().setBackground(java.awt.Color.BLACK);
    }
    
    public void setAllRadioButtonUnselected()
    {
        menuScientificCalculatorRadioButton.setSelected(false);
        menuComplexNumberRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuWelcomeJLabel = new javax.swing.JLabel();
        menuSelectModeOfOperationJLabel = new javax.swing.JLabel();
        menuScientificCalculatorRadioButton = new javax.swing.JRadioButton();
        menuComplexNumberRadioButton = new javax.swing.JRadioButton();
        menuEquationSolverRadioButton = new javax.swing.JRadioButton();
        menuNumberSystemCalculationRadioButton = new javax.swing.JRadioButton();
        menuNumberSystemConversionRadioButton = new javax.swing.JRadioButton();
        menuConverterRadioButton = new javax.swing.JRadioButton();
        menuExitButton = new javax.swing.JButton();
        menuAboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setName("Menu_Frame"); // NOI18N

        menuWelcomeJLabel.setFont(new java.awt.Font("Engravers MT", 1, 17)); // NOI18N
        menuWelcomeJLabel.setForeground(new java.awt.Color(0, 255, 0));
        menuWelcomeJLabel.setText("                                     WELCOME");

        menuSelectModeOfOperationJLabel.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        menuSelectModeOfOperationJLabel.setForeground(new java.awt.Color(0, 255, 0));
        menuSelectModeOfOperationJLabel.setText("                  PLEASE SELECT YOUR MODE OF OPERATION :");

        menuScientificCalculatorRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuScientificCalculatorRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuScientificCalculatorRadioButton.setForeground(new java.awt.Color(255, 0, 153));
        menuScientificCalculatorRadioButton.setText("CALCULATOR : SCIENTIFIC CALCULATION MODE");
        menuScientificCalculatorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuScientificCalculatorRadioButtonActionPerformed(evt);
            }
        });

        menuComplexNumberRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuComplexNumberRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuComplexNumberRadioButton.setForeground(new java.awt.Color(0, 255, 255));
        menuComplexNumberRadioButton.setText("CALCULATOR : COMPLEX NUMBER MODE");
        menuComplexNumberRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComplexNumberRadioButtonActionPerformed(evt);
            }
        });

        menuEquationSolverRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuEquationSolverRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuEquationSolverRadioButton.setForeground(new java.awt.Color(0, 255, 0));
        menuEquationSolverRadioButton.setText("CALCULATOR : EQUATION SOLVING MODE");
        menuEquationSolverRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEquationSolverRadioButtonActionPerformed(evt);
            }
        });

        menuNumberSystemCalculationRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuNumberSystemCalculationRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuNumberSystemCalculationRadioButton.setForeground(new java.awt.Color(255, 255, 0));
        menuNumberSystemCalculationRadioButton.setText("CALCULATOR : NUMBER SYSTEM CALCULATION MODE");
        menuNumberSystemCalculationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNumberSystemCalculationRadioButtonActionPerformed(evt);
            }
        });

        menuNumberSystemConversionRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuNumberSystemConversionRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuNumberSystemConversionRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        menuNumberSystemConversionRadioButton.setText("CALCULATOR : NUMBER SYSTEM CONVERSION MODE");
        menuNumberSystemConversionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNumberSystemConversionRadioButtonActionPerformed(evt);
            }
        });

        menuConverterRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        menuConverterRadioButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuConverterRadioButton.setForeground(new java.awt.Color(255, 0, 0));
        menuConverterRadioButton.setText("CONVERTER MODE");
        menuConverterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConverterRadioButtonActionPerformed(evt);
            }
        });

        menuExitButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuExitButton.setText("EXIT");
        menuExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitButtonActionPerformed(evt);
            }
        });

        menuAboutButton.setFont(new java.awt.Font("Lucida Handwriting", 1, 15)); // NOI18N
        menuAboutButton.setText("ABOUT");
        menuAboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuWelcomeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuSelectModeOfOperationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuComplexNumberRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuScientificCalculatorRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menuExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(menuAboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menuEquationSolverRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menuNumberSystemCalculationRadioButton)
                                .addComponent(menuNumberSystemConversionRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menuConverterRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menuWelcomeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSelectModeOfOperationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(menuComplexNumberRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menuScientificCalculatorRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuEquationSolverRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuNumberSystemCalculationRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuNumberSystemConversionRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuConverterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuExitButton)
                    .addComponent(menuAboutButton))
                .addGap(34, 34, 34))
        );

        setSize(new java.awt.Dimension(551, 391));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuExitButtonActionPerformed
    {//GEN-HEADEREND:event_menuExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitButtonActionPerformed

    private void menuScientificCalculatorRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuScientificCalculatorRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuScientificCalculatorRadioButtonActionPerformed
        // TODO add your handling code here:
        menuComplexNumberRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
        this.setVisible(false);
        CALCULATOR object = new CALCULATOR();
        object.setVisible(true);
    }//GEN-LAST:event_menuScientificCalculatorRadioButtonActionPerformed

    private void menuComplexNumberRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuComplexNumberRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuComplexNumberRadioButtonActionPerformed

        menuScientificCalculatorRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
                this.setVisible(false);
                CALCULATOR_COMPLEX_MODE object = new CALCULATOR_COMPLEX_MODE();
        object.setVisible(true);
    }//GEN-LAST:event_menuComplexNumberRadioButtonActionPerformed

    private void menuEquationSolverRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuEquationSolverRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuEquationSolverRadioButtonActionPerformed
        // TODO add your handling code here:
        //setAllRadioButtonUnselected();
        menuScientificCalculatorRadioButton.setSelected(false);
        menuComplexNumberRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
                this.setVisible(false);
                CALCULATOR_EQUN_MODE object = new CALCULATOR_EQUN_MODE();
        object.setVisible(true);
    }//GEN-LAST:event_menuEquationSolverRadioButtonActionPerformed

    private void menuNumberSystemCalculationRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuNumberSystemCalculationRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuNumberSystemCalculationRadioButtonActionPerformed
        // TODO add your handling code here:
        //setAllRadioButtonUnselected();
        menuScientificCalculatorRadioButton.setSelected(false);
        menuComplexNumberRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        //menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
                this.setVisible(false);
                    CALCULATOR_NumberSystemCalculation object = new CALCULATOR_NumberSystemCalculation();
        object.setVisible(true);
    }//GEN-LAST:event_menuNumberSystemCalculationRadioButtonActionPerformed

    private void menuNumberSystemConversionRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuNumberSystemConversionRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuNumberSystemConversionRadioButtonActionPerformed
        // TODO add your handling code here:
        //setAllRadioButtonUnselected();
        menuScientificCalculatorRadioButton.setSelected(false);
        menuComplexNumberRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        //menuNumberSystemConversionRadioButton.setSelected(false);
        menuConverterRadioButton.setSelected(false);
                this.setVisible(false);
                CALCULATOR_NumberSystemConvert object = new CALCULATOR_NumberSystemConvert();
        object.setVisible(true);
    }//GEN-LAST:event_menuNumberSystemConversionRadioButtonActionPerformed

    private void menuConverterRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuConverterRadioButtonActionPerformed
    {//GEN-HEADEREND:event_menuConverterRadioButtonActionPerformed
        // TODO add your handling code here:
        //setAllRadioButtonUnselected();
        menuScientificCalculatorRadioButton.setSelected(false);
        menuComplexNumberRadioButton.setSelected(false);
        menuEquationSolverRadioButton.setSelected(false);
        menuNumberSystemCalculationRadioButton.setSelected(false);
        menuNumberSystemConversionRadioButton.setSelected(false);
        //menuConverterRadioButton.setSelected(false);
                this.setVisible(false);
                CONVERTER object = new CONVERTER();
        object.setVisible(true);
    }//GEN-LAST:event_menuConverterRadioButtonActionPerformed

    private void menuAboutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuAboutButtonActionPerformed
    {//GEN-HEADEREND:event_menuAboutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        About object = new About();
        object.setVisible(true);
    }//GEN-LAST:event_menuAboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menuAboutButton;
    private javax.swing.JRadioButton menuComplexNumberRadioButton;
    private javax.swing.JRadioButton menuConverterRadioButton;
    private javax.swing.JRadioButton menuEquationSolverRadioButton;
    private javax.swing.JButton menuExitButton;
    private javax.swing.JRadioButton menuNumberSystemCalculationRadioButton;
    private javax.swing.JRadioButton menuNumberSystemConversionRadioButton;
    private javax.swing.JRadioButton menuScientificCalculatorRadioButton;
    private javax.swing.JLabel menuSelectModeOfOperationJLabel;
    private javax.swing.JLabel menuWelcomeJLabel;
    // End of variables declaration//GEN-END:variables
}
